// Build the bundled gallery from the PixelCraft example corpus.
//
// Runs at build time with the Node engine, because it writes real PNG and GIF files.
// The app itself never does this — at runtime everything renders in the browser.
//
// Output:
//   public/gallery/<slug>.pc     the program (fetched on demand, so it stays out of the JS bundle)
//   public/gallery/<slug>.png    a still preview
//   public/gallery/<slug>.gif    a looping preview, for animated programs
//   src/lib/gallery-data.ts      metadata only — small enough to ship to the client
import { renderAnimation, renderSource } from '@pixelplace/pixelcraft'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const webRoot = join(here, '..')
const SOURCE_DIR = process.env.PIXELCRAFT_EXAMPLES ?? 'C:/ClaudeProjects/CodingArt/examples'
const OUT_DIR = join(webRoot, 'public', 'gallery')
const DATA_FILE = join(webRoot, 'src', 'lib', 'gallery-data.ts')

// Thumbnails target roughly this many pixels on the long edge, at an integer scale
// so the art stays crisp. Pixel art must never be resampled.
const TARGET_EDGE = 320

if (!existsSync(SOURCE_DIR)) {
  console.error(`build-gallery: no example corpus at ${SOURCE_DIR}`)
  console.error('Set PIXELCRAFT_EXAMPLES to point at it.')
  process.exit(1)
}

const titleCase = (slug) =>
  slug
    .replace(/_v(\d+[a-z]?)$/i, ' v$1')
    .split('_')
    .map((word) => (/^v\d/i.test(word) ? word : word.charAt(0).toUpperCase() + word.slice(1)))
    .join(' ')

/** Tags come from what the program actually uses, so they never lie about content. */
function deriveTags(source, result) {
  const tags = []
  const has = (pattern) => new RegExp(pattern, 'm').test(source)

  if (result.hasAnimation) tags.push('animated')
  else tags.push('still')
  if (has('^\\s*timeline\\b')) tags.push('timeline')
  if (has('^\\s*emit\\b')) tags.push('particles')
  if (has('^\\s*tileset\\b') || has('^\\s*tilemap\\b')) tags.push('tileset')
  if (has('^\\s*(font|text)\\b')) tags.push('text')
  if (has('^\\s*(layer|with)\\b')) tags.push('layers')
  if (has('^\\s*(scatter|repeat)\\b')) tags.push('procedural')
  if (has('^\\s*(box|dock)\\b')) tags.push('layout')
  if (has('\\b(pow|noise01|smoothstep|lerp|ease_in_out)\\(')) tags.push('expressions')
  if (result.width <= 24 && result.height <= 24) tags.push('tiny')
  return tags
}

rmSync(OUT_DIR, { recursive: true, force: true })
mkdirSync(OUT_DIR, { recursive: true })

const files = readdirSync(SOURCE_DIR).filter((f) => f.endsWith('.txt')).sort()
const entries = []
const skipped = []

for (const file of files) {
  const slug = file.replace(/\.txt$/, '').replace(/[^a-z0-9_-]/gi, '-').toLowerCase()
  const source = readFileSync(join(SOURCE_DIR, file), 'utf8')

  const probe = renderSource(source)
  if (!probe.ok) {
    skipped.push(`${file}: ${probe.errors.slice(0, 1).map((e) => `${e.code} ${e.message}`).join('')}`)
    continue
  }

  const scale = Math.max(1, Math.min(12, Math.round(TARGET_EDGE / Math.max(probe.width, probe.height))))
  const still = renderSource(source, { scale })
  writeFileSync(join(OUT_DIR, `${slug}.png`), Buffer.from(still.png, 'base64'))
  writeFileSync(join(OUT_DIR, `${slug}.pc`), source, 'utf8')

  let hasGif = false
  if (probe.hasAnimation) {
    const animated = renderAnimation(source, { scale, fps: 12 })
    if (animated.ok) {
      writeFileSync(join(OUT_DIR, `${slug}.gif`), Buffer.from(animated.gif, 'base64'))
      hasGif = true
    }
  }

  entries.push({
    slug,
    title: titleCase(slug),
    width: probe.width,
    height: probe.height,
    frameCount: probe.hasAnimation ? probe.frameCount : 0,
    scale,
    hasGif,
    tags: deriveTags(source, probe),
    lines: source.split('\n').filter((l) => l.trim() !== '' && !l.trim().startsWith('#')).length
  })
}

const banner = `// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Metadata only: the programs themselves live in public/gallery/<slug>.pc and are
// fetched on demand, so ${entries.length} examples cost the JS bundle almost nothing.
`

const body = `export interface GalleryEntry {
  slug: string
  title: string
  width: number
  height: number
  /** 0 for a still program. */
  frameCount: number
  /** Integer upscale the bundled preview images were rendered at. */
  scale: number
  hasGif: boolean
  tags: string[]
  /** Non-blank, non-comment lines — a rough sense of how much program this is. */
  lines: number
}

export const GALLERY_DATA: GalleryEntry[] = ${JSON.stringify(entries, null, 2)}
`

writeFileSync(DATA_FILE, banner + '\n' + body, 'utf8')

console.log(`build-gallery: ${entries.length} example(s) written to public/gallery/`)
console.log(`  ${entries.filter((e) => e.hasGif).length} animated, ${entries.filter((e) => !e.hasGif).length} still`)
if (skipped.length > 0) {
  console.log(`  skipped ${skipped.length}:`)
  for (const line of skipped) console.log(`    ${line}`)
}
