// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Metadata only: the programs themselves live in public/gallery/<slug>.pc and are
// fetched on demand, so 58 examples cost the JS bundle almost nothing.

export interface GalleryEntry {
  slug: string
  title: string
  width: number
  height: number
  /** 0 for a still program. */
  frameCount: number
  /** Integer upscale the bundled preview images were rendered at. */
  scale: number
  hasGif: boolean
  tags: string[]
  /** Non-blank, non-comment lines — a rough sense of how much program this is. */
  lines: number
}

export const GALLERY_DATA: GalleryEntry[] = [
  {
    "slug": "adventurer_idle_v2",
    "title": "Adventurer Idle v2",
    "width": 28,
    "height": 24,
    "frameCount": 10,
    "scale": 11,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers"
    ],
    "lines": 135
  },
  {
    "slug": "arcane_lance_emit_spell",
    "title": "Arcane Lance Emit Spell",
    "width": 40,
    "height": 24,
    "frameCount": 8,
    "scale": 8,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers"
    ],
    "lines": 138
  },
  {
    "slug": "arcane_lance_emit_spell_v2",
    "title": "Arcane Lance Emit Spell v2",
    "width": 44,
    "height": 24,
    "frameCount": 9,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers"
    ],
    "lines": 166
  },
  {
    "slug": "aurora_waystation",
    "title": "Aurora Waystation",
    "width": 64,
    "height": 64,
    "frameCount": 0,
    "scale": 5,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 127
  },
  {
    "slug": "campfire_clearing_timeline",
    "title": "Campfire Clearing Timeline",
    "width": 52,
    "height": 34,
    "frameCount": 32,
    "scale": 6,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 111
  },
  {
    "slug": "campfire_clearing_timeline_wave",
    "title": "Campfire Clearing Timeline Wave",
    "width": 52,
    "height": 34,
    "frameCount": 32,
    "scale": 6,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 107
  },
  {
    "slug": "codex_aetherport_megacity",
    "title": "Codex Aetherport Megacity",
    "width": 96,
    "height": 64,
    "frameCount": 6,
    "scale": 3,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "procedural"
    ],
    "lines": 281
  },
  {
    "slug": "codex_aetherport_megacity_v2",
    "title": "Codex Aetherport Megacity v2",
    "width": 112,
    "height": 72,
    "frameCount": 8,
    "scale": 3,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "procedural"
    ],
    "lines": 311
  },
  {
    "slug": "codex_night_gardener",
    "title": "Codex Night Gardener",
    "width": 80,
    "height": 56,
    "frameCount": 48,
    "scale": 4,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 155
  },
  {
    "slug": "comet_observatory",
    "title": "Comet Observatory",
    "width": 48,
    "height": 48,
    "frameCount": 0,
    "scale": 7,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 113
  },
  {
    "slug": "coral_reef",
    "title": "Coral Reef",
    "width": 48,
    "height": 48,
    "frameCount": 0,
    "scale": 7,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 215
  },
  {
    "slug": "cozy_cottage",
    "title": "Cozy Cottage",
    "width": 24,
    "height": 24,
    "frameCount": 3,
    "scale": 12,
    "hasGif": true,
    "tags": [
      "animated",
      "procedural",
      "tiny"
    ],
    "lines": 90
  },
  {
    "slug": "ember_bolt_frames_spell",
    "title": "Ember Bolt Frames Spell",
    "width": 42,
    "height": 22,
    "frameCount": 9,
    "scale": 8,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers"
    ],
    "lines": 55
  },
  {
    "slug": "enemy_roster_strip",
    "title": "Enemy Roster Strip",
    "width": 96,
    "height": 34,
    "frameCount": 0,
    "scale": 3,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural",
      "layout"
    ],
    "lines": 122
  },
  {
    "slug": "expression_signal_array",
    "title": "Expression Signal Array",
    "width": 32,
    "height": 32,
    "frameCount": 0,
    "scale": 10,
    "hasGif": false,
    "tags": [
      "still",
      "procedural"
    ],
    "lines": 32
  },
  {
    "slug": "fable_ink_sea",
    "title": "Fable Ink Sea",
    "width": 80,
    "height": 56,
    "frameCount": 48,
    "scale": 4,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 187
  },
  {
    "slug": "fable_ink_sea_v2",
    "title": "Fable Ink Sea v2",
    "width": 80,
    "height": 56,
    "frameCount": 48,
    "scale": 4,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 204
  },
  {
    "slug": "fireball_spell",
    "title": "Fireball Spell",
    "width": 32,
    "height": 20,
    "frameCount": 6,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "procedural"
    ],
    "lines": 151
  },
  {
    "slug": "fireball_spell_v2",
    "title": "Fireball Spell v2",
    "width": 32,
    "height": 20,
    "frameCount": 8,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "procedural"
    ],
    "lines": 82
  },
  {
    "slug": "fireball_spell_v2b",
    "title": "Fireball Spell v2b",
    "width": 32,
    "height": 20,
    "frameCount": 6,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "procedural"
    ],
    "lines": 151
  },
  {
    "slug": "hero_state_sheet_v2",
    "title": "Hero State Sheet v2",
    "width": 48,
    "height": 28,
    "frameCount": 16,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 124
  },
  {
    "slug": "hud_layout_panels",
    "title": "Hud Layout Panels",
    "width": 72,
    "height": 42,
    "frameCount": 0,
    "scale": 4,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "layout"
    ],
    "lines": 110
  },
  {
    "slug": "hud_minipack",
    "title": "Hud Minipack",
    "width": 64,
    "height": 40,
    "frameCount": 0,
    "scale": 5,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 111
  },
  {
    "slug": "icon_sheet_basics",
    "title": "Icon Sheet Basics",
    "width": 58,
    "height": 46,
    "frameCount": 0,
    "scale": 6,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 120
  },
  {
    "slug": "intrinsics_ai_ergonomics_minipack_showcase",
    "title": "Intrinsics Ai Ergonomics Minipack Showcase",
    "width": 48,
    "height": 28,
    "frameCount": 48,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 70
  },
  {
    "slug": "intrinsics_hypnotic_iris_loop",
    "title": "Intrinsics Hypnotic Iris Loop",
    "width": 33,
    "height": 33,
    "frameCount": 32,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "layers",
      "expressions"
    ],
    "lines": 29
  },
  {
    "slug": "intrinsics_reactor_lockdown_timeline",
    "title": "Intrinsics Reactor Lockdown Timeline",
    "width": 64,
    "height": 36,
    "frameCount": 48,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "expressions"
    ],
    "lines": 76
  },
  {
    "slug": "intrinsics_tempest_conduit_timeline",
    "title": "Intrinsics Tempest Conduit Timeline",
    "width": 56,
    "height": 34,
    "frameCount": 48,
    "scale": 6,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 83
  },
  {
    "slug": "intrinsics_void_portal_blossom_timeline",
    "title": "Intrinsics Void Portal Blossom Timeline",
    "width": 56,
    "height": 40,
    "frameCount": 64,
    "scale": 6,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 80
  },
  {
    "slug": "item_icons_showcase_v2",
    "title": "Item Icons Showcase v2",
    "width": 40,
    "height": 24,
    "frameCount": 16,
    "scale": 8,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 80
  },
  {
    "slug": "lantern_pond",
    "title": "Lantern Pond",
    "width": 48,
    "height": 48,
    "frameCount": 0,
    "scale": 7,
    "hasGif": false,
    "tags": [
      "still",
      "layers"
    ],
    "lines": 172
  },
  {
    "slug": "layers_push_pop_animation_demo",
    "title": "Layers Push Pop Animation Demo",
    "width": 20,
    "height": 12,
    "frameCount": 2,
    "scale": 12,
    "hasGif": true,
    "tags": [
      "animated",
      "layers",
      "tiny"
    ],
    "lines": 40
  },
  {
    "slug": "layers_push_pop_demo",
    "title": "Layers Push Pop Demo",
    "width": 16,
    "height": 10,
    "frameCount": 0,
    "scale": 12,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "tiny"
    ],
    "lines": 15
  },
  {
    "slug": "lerp_ease_skydart_demo",
    "title": "Lerp Ease Skydart Demo",
    "width": 32,
    "height": 20,
    "frameCount": 24,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 72
  },
  {
    "slug": "lighthouse_cove",
    "title": "Lighthouse Cove",
    "width": 32,
    "height": 24,
    "frameCount": 4,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "procedural"
    ],
    "lines": 58
  },
  {
    "slug": "moon_jelly_bloom_loop",
    "title": "Moon Jelly Bloom Loop",
    "width": 48,
    "height": 40,
    "frameCount": 32,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 144
  },
  {
    "slug": "mushroom_glade",
    "title": "Mushroom Glade",
    "width": 48,
    "height": 48,
    "frameCount": 0,
    "scale": 7,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 213
  },
  {
    "slug": "noise_dither_micro_showcase",
    "title": "Noise Dither Micro Showcase",
    "width": 24,
    "height": 16,
    "frameCount": 0,
    "scale": 12,
    "hasGif": false,
    "tags": [
      "still",
      "procedural",
      "expressions",
      "tiny"
    ],
    "lines": 12
  },
  {
    "slug": "noise_dither_micro_showcase_anim",
    "title": "Noise Dither Micro Showcase Anim",
    "width": 24,
    "height": 16,
    "frameCount": 12,
    "scale": 12,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "layers",
      "procedural",
      "expressions",
      "tiny"
    ],
    "lines": 20
  },
  {
    "slug": "opus5_deep_field",
    "title": "Opus5 Deep Field",
    "width": 64,
    "height": 48,
    "frameCount": 24,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 59
  },
  {
    "slug": "palette_variant_postcard",
    "title": "Palette Variant Postcard",
    "width": 92,
    "height": 34,
    "frameCount": 0,
    "scale": 3,
    "hasGif": false,
    "tags": [
      "still",
      "layers"
    ],
    "lines": 78
  },
  {
    "slug": "pixelcraft_logo_badge",
    "title": "Pixelcraft Logo Badge",
    "width": 64,
    "height": 64,
    "frameCount": 0,
    "scale": 5,
    "hasGif": false,
    "tags": [
      "still",
      "layers"
    ],
    "lines": 66
  },
  {
    "slug": "rainy_alley_tilemap_timeline",
    "title": "Rainy Alley Tilemap Timeline",
    "width": 64,
    "height": 40,
    "frameCount": 24,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "tileset",
      "layers",
      "expressions"
    ],
    "lines": 123
  },
  {
    "slug": "rainy_alley_tilemap_timeline_loop_rain",
    "title": "Rainy Alley Tilemap Timeline Loop Rain",
    "width": 64,
    "height": 40,
    "frameCount": 24,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "tileset",
      "layers",
      "expressions"
    ],
    "lines": 142
  },
  {
    "slug": "relic_orbit_spell_timeline_v3",
    "title": "Relic Orbit Spell Timeline v3",
    "width": 36,
    "height": 24,
    "frameCount": 16,
    "scale": 9,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 96
  },
  {
    "slug": "relic_orbit_spell_v2",
    "title": "Relic Orbit Spell v2",
    "width": 36,
    "height": 24,
    "frameCount": 16,
    "scale": 9,
    "hasGif": true,
    "tags": [
      "animated",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 83
  },
  {
    "slug": "ritual_vfx_loop",
    "title": "Ritual Vfx Loop",
    "width": 48,
    "height": 48,
    "frameCount": 32,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 104
  },
  {
    "slug": "showcase",
    "title": "Showcase",
    "width": 64,
    "height": 48,
    "frameCount": 0,
    "scale": 5,
    "hasGif": false,
    "tags": [
      "still",
      "layers",
      "procedural"
    ],
    "lines": 167
  },
  {
    "slug": "star_whale_drift",
    "title": "Star Whale Drift",
    "width": 64,
    "height": 40,
    "frameCount": 48,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "expressions"
    ],
    "lines": 77
  },
  {
    "slug": "sunrise_lake",
    "title": "Sunrise Lake",
    "width": 24,
    "height": 24,
    "frameCount": 0,
    "scale": 12,
    "hasGif": false,
    "tags": [
      "still",
      "procedural",
      "tiny"
    ],
    "lines": 39
  },
  {
    "slug": "tilemap_mvp_terrain",
    "title": "Tilemap Mvp Terrain",
    "width": 24,
    "height": 16,
    "frameCount": 0,
    "scale": 12,
    "hasGif": false,
    "tags": [
      "still",
      "tileset",
      "tiny"
    ],
    "lines": 33
  },
  {
    "slug": "tilemap_paint_mode_weighted_overlay",
    "title": "Tilemap Paint Mode Weighted Overlay",
    "width": 40,
    "height": 24,
    "frameCount": 24,
    "scale": 8,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "tileset"
    ],
    "lines": 69
  },
  {
    "slug": "tileset_forest_village",
    "title": "Tileset Forest Village",
    "width": 64,
    "height": 64,
    "frameCount": 0,
    "scale": 5,
    "hasGif": false,
    "tags": [
      "still",
      "tileset",
      "layers"
    ],
    "lines": 170
  },
  {
    "slug": "v01_teaser_logo_forge",
    "title": "v01 Teaser Logo Forge",
    "width": 40,
    "height": 24,
    "frameCount": 24,
    "scale": 8,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 105
  },
  {
    "slug": "v01_teaser_palette_pattern",
    "title": "v01 Teaser Palette Pattern",
    "width": 64,
    "height": 64,
    "frameCount": 24,
    "scale": 5,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "layers",
      "procedural",
      "expressions"
    ],
    "lines": 84
  },
  {
    "slug": "weather_loop_rain",
    "title": "Weather Loop Rain",
    "width": 48,
    "height": 32,
    "frameCount": 24,
    "scale": 7,
    "hasGif": true,
    "tags": [
      "animated",
      "timeline",
      "particles",
      "layers",
      "expressions"
    ],
    "lines": 78
  },
  {
    "slug": "winter_landscape_layered",
    "title": "Winter Landscape Layered",
    "width": 32,
    "height": 32,
    "frameCount": 4,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated",
      "layers"
    ],
    "lines": 68
  },
  {
    "slug": "winter_landscape_modern",
    "title": "Winter Landscape Modern",
    "width": 32,
    "height": 32,
    "frameCount": 8,
    "scale": 10,
    "hasGif": true,
    "tags": [
      "animated"
    ],
    "lines": 66
  }
]
